[add] <toptopコンポーネントの追加>
Kyutech-C3/web pull request #4
Opened 2021-09-12 10:44 UTC by sha-ce

まだ未完成ですが。。。進捗報告を兼ねて

2021-09-15 11:29 UTC, sha-ce commented
hooperインストールしました
カルーセルが超簡単に！！！

2021-10-03 11:42 UTC, citrus-candy requested changes

2021-10-03 11:42 UTC, citrus-candy commented on components/TopTop.vue
> +  <div>
一番上の階層の`div`は消してもいいです

2021-10-03 11:42 UTC, citrus-candy commented on components/TopTop.vue
> +              <a :href="allNewsLink">一覧を見る</a>
Nuxtはルーティング専用のタグがあるので
``` html
<nuxt-link to="/news">一覧を見る</nuxt-link>
```
としてください

2021-10-03 11:42 UTC, citrus-candy commented on components/TopTop.vue
> +            </a>
``` html
<nuxt-link to=`/news/${news.id}`>
  {{ news.date + ' ' + news.content }}
</nuxt-link>
```

2021-10-03 11:42 UTC, citrus-candy commented on components/TopTop.vue
> +              </a>
``` html
<nuxt-link to="slides[idx].link">
  <img :src="slides[idx].img"/>
</nuxt-link>

```

2021-10-03 11:42 UTC, citrus-candy commented on components/TopTop.vue
> +              <a :href="allNewsLink">一覧を見る</a>
``` html
<nuxt-link to="/news">一覧を見る</nuxt-link>
```

2021-10-03 11:42 UTC, citrus-candy commented on components/TopTop.vue
> +            </a>
``` html
<nuxt-link to=`/news/${news.id}`>
  {{ news.date + ' ' + news.content }}
</nuxt-link>
```

2021-10-03 11:42 UTC, citrus-candy commented on components/TopTop.vue
> +				content: 'オフィシャルサイト更新！！'
newsには固有のIDがあるので、仮のIDとして
``` javascript
id: 0
```
を追加してください

2021-10-03 11:42 UTC, citrus-candy commented on components/TopTop.vue
> +      topNewsLink: '#topnews',
``` javascript
allNewsLink: '#allnews',
topNewsLink: '#topnews',
```
この2つは使わないと思うので消していいです

2021-10-03 12:07 UTC, sha-ce commented
一応ふぃる先輩のお告げをもらい修正を完了しました．
よさそうならばマージお願いします．

2021-10-03 12:12 UTC, citrus-candy commented on components/TopTop.vue
> +              <nuxt-link>
`to="slides[idx].link"`が抜けてます

2021-10-03 12:14 UTC, sha-ce commented on components/TopTop.vue
> +              <nuxt-link>
すみませんすぐ修正します

2021-10-03 12:29 UTC, sha-ce commented
修正しました確認お願いします

2021-10-03 12:30 UTC, citrus-candy approved these changes

2021-10-03 12:37 UTC, Prokuma commented
「何をしたか（'いろんな部分を修正'でもいい）」をコミットメッセージだけでわかるように書いた方がいい（自分も適当に書くことが多いが）
コードの方はOKです。

2021-10-03 12:38 UTC, Prokuma approved these changes

2021-10-03 12:38 UTC, merged